---
stages:
  - deploy

deploy-job:
  stage: deploy
  script:
    - eval "$(ssh-agent -s)" > /dev/null 2>&1
    - ssh-add <(echo "$SSH_PRIVATE_KEY") > /dev/null 2>&1
    - mkdir -p ~/.ssh && echo -e "Host *\n\tStrictHostKeyChecking no\n\tLogLevel=quiet\n\n" >> ~/.ssh/config
    - rsync --itemize-changes --verbose --human-readable --times --checksum --recursive --delete --exclude-from=/etc/rsyncignore --delete-excluded . ssh://alexxas@app.alexgrigu.ru::/var/www/wordpress/
    - rc=$?; if [[ $rc != 0 ]]; then echo "rsync failed with $rc"; exit 1; fi
